# Site settings
title: dnlserrano
email: danieljdserrano@gmail.com
description: "A blog about code and life in general"
url: "https://dnlserrano.github.io/"
twitter_username: dnlserrano
github_username:  dnlserrano
linkedin_username: danieljdserrano
instagram_username: dnlserrano
hackernews_username: dnlserrano
huggingface_username: dnlserrano

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins:
  - jekyll-paginate
  - jekyll-time-to-read

kramdown:
  input: GFM
